version: "3.8"

services:
  php:
    image: ghcr.io/blumilksoftware/php:8.0
    container_name: identifier-php
    working_dir: /application
    user: ${CURRENT_UID}
    volumes:
      - .:/application
